### ISSUE TITLE
OS 0.9.2 (YScript)

### ISSUE THREAD

**Issue by aurorastarchild** [typhartez/avsitter-plugin-osprop#1]
Hi @typhartez - just facec this challenge and, of course, the issues still in Mantis as 'new' since 2018...
Tried this +  the workaround here: https://github.com/AVsitter/AVsitter/issues/74 + another workaround about linking the wear prop to another prim and only linked-edit-rotating the attachment.
None of them worked.

Any plans to update this for 0.9.2 & YScript?

**Comment by Parsalin** [comment]
it looks like if you change 

prop_rotation = (vector)llList2String(data, 3);

to 

prop_rotation = llList2Vector(data, 3);

itll work as intended...

**Comment by typhartez** [comment]
Hi @aurorastarchild 

> Any plans to update this for 0.9.2 & YScript?

Unfortunately, I am on a long OS hiatus and not played with any script since more than a year.

Anyway, if you confirm the above workaround is enough to make the script compatible with YScript, I'll do the edit so that it's usable for others without having the need to edit the code :)

It's weird the `llList2String()` with a cast does not work but, not being able to check, I'll take it as granted :)

**Comment by aurorastarchild** [comment]
Awww @typhartez do come back some time! We need talented scripters here :D 
Yes, the tweak works. It is a bit odd because then it takes the position from the adjustment done when inventory-wear-ing + rotation from AVpos.
So with the tweak, person would have to:
1. Attach **from inventory** while on the pose (this is as per avisitter standard anyway).
2. Copy + paste position + rotation values on AVpos
The wear prop will ignore the position values from AVpos, but take the rotation ones

**Comment by typhartez** [comment]
Mmhmm, I remember the process was a bit odd, but couldn't find a better way without breaking how props work with avsitter.

Anyway, thinking again about it, I wont report the workaround upstream because I'm not sure that will still work with older versions (XScript). But I keep a note about it for the day I'll feel like coming back in OS. And so, I keep the issue opened as well.

**Comment by typhartez** [comment]
@aurorastarchild

After a few tries and our discussion in world, I confirm the plugin works. Maybe it's a usage issue, so I detail how I tried:
1. Wear the attachment, set it to the needed rotation and ensure the rotation (in vector format) is set in `AVpos` notecard
2. Detach attachment and drop it in the sitter

The object can have a zero rotation in its properties (I tried by rezzing the object, setting its rotation to 0, take back in inventory and drop it in the sitter), the rotation is overridden.

Or maybe it's an OpenSim version issue. This works on all stable releases of OpenSim (until 0.9.2.x). I haven't tried on 0.9.3 because I don't use it (even if it has some nice fixes and features). Please check if the issue exists on 0.9.2 as well.
